spring.application.name=kvlc-secure

logging.level.org.springframework.web=info

#prod
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/kvcl_release

#dev
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/kvcl_dev

#local env
#server.port=8060
#spring.datasource.url=jdbc:postgresql://localhost:5432/kvcl_restore

spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.hikari.connection-timeout=180000
spring.datasource.hikari.maximum-pool-size=20

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server.max-http-request-header-size=50MB
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size = 50MB

spring.mvc.favicon.enabled=false

server.ssl.key-store-type=JKS
# The path to the keystore containing the certificate
server.ssl.key-store=classpath:keystore/suchith.jks
# The password used to generate the certificate
server.ssl.key-store-password=password
# The alias mapped to the certificate
server.ssl.key-alias=suchith